bumps:
  - file: package.json
    json:
      - path: "version"
        semver: true

annotatedTags: true
commitAuthor:
  name: "Benjamin Houdu"
  email: "benjamin.houdu@gmail.com"
commitMessage: "chore(release): bump version to {version} [skip ci]"

publish:
  enabled: true
  registry: https://registry.npmjs.org/
  token: $NPM_TOKEN

changelog:
  sort: desc
  exclude:
    - '^chore\:*'
  include:
    - '^build\:*'
    - '^ci\:*'
    - '^docs\:*'
    - '^feat\:*'
    - '^feat\!\:*'
    - '^feat\(*\)\:*'
    - '^feat\(*\)\!\:*'
    - '^fix\:*'
    - '^fix\!\:*'
    - '^fix\(*\)\:*'
    - '^fix\(*\)\!\:*'
    - '^perf\:*'
    - '^refactor\:*'
    - '^test\:*'

git:
  ignoreDetached: false
  ignoreShallow: true
  pushOptions:
    - option: ci.skip
      skipBranch: true
      skipTag: false
